//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBP.Domain.SharedKernel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBP.Domain.SharedKernel.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este horario já se encontra preenchido para este Funcionário..
        /// </summary>
        public static string AgendamentoJaExiste {
            get {
                return ResourceManager.GetString("AgendamentoJaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro é obrigatório..
        /// </summary>
        public static string BairroObrigatorio {
            get {
                return ResourceManager.GetString("BairroObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo deve conter no máximo {1} caracteres..
        /// </summary>
        public static string CampoComMaximoDeCaracteresPermitidoVM {
            get {
                return ResourceManager.GetString("CampoComMaximoDeCaracteresPermitidoVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo deve conter no mínimo {1} caracteres..
        /// </summary>
        public static string CampoComMinimoDeCaracteresPermitidoVM {
            get {
                return ResourceManager.GetString("CampoComMinimoDeCaracteresPermitidoVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo é obrigatório..
        /// </summary>
        public static string CampoObrigatorio {
            get {
                return ResourceManager.GetString("CampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP é inválido..
        /// </summary>
        public static string CEPInvalido {
            get {
                return ResourceManager.GetString("CEPInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP é obrigatório..
        /// </summary>
        public static string CepObrigatorio {
            get {
                return ResourceManager.GetString("CepObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP em tamanho incorreto..
        /// </summary>
        public static string CepTamanhoInvalido {
            get {
                return ResourceManager.GetString("CepTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade é obrigatório..
        /// </summary>
        public static string CidadeObrigatorio {
            get {
                return ResourceManager.GetString("CidadeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cliente é inválido..
        /// </summary>
        public static string ClienteInvalido {
            get {
                return ResourceManager.GetString("ClienteInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ inválido..
        /// </summary>
        public static string CNPJInvalido {
            get {
                return ResourceManager.GetString("CNPJInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ já cadastrado para outra empresa..
        /// </summary>
        public static string CNPJJaExiste {
            get {
                return ResourceManager.GetString("CNPJJaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CNPJ é obrigatório..
        /// </summary>
        public static string CNPJObrigatorio {
            get {
                return ResourceManager.GetString("CNPJObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ em tamanho incorreto..
        /// </summary>
        public static string CNPJTamanhoInvalido {
            get {
                return ResourceManager.GetString("CNPJTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A confirmação de senha é obrigatória..
        /// </summary>
        public static string ConfirmarSenhaObrigatoria {
            get {
                return ResourceManager.GetString("ConfirmarSenhaObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF inválido..
        /// </summary>
        public static string CPFInvalido {
            get {
                return ResourceManager.GetString("CPFInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF já cadastrado para outra pessoa..
        /// </summary>
        public static string CPFJaExiste {
            get {
                return ResourceManager.GetString("CPFJaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF é obrigatório..
        /// </summary>
        public static string CPFObrigatorio {
            get {
                return ResourceManager.GetString("CPFObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF em tamanho incorreto..
        /// </summary>
        public static string CPFTamanhoInvalido {
            get {
                return ResourceManager.GetString("CPFTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de agendamento é inválida..
        /// </summary>
        public static string DataDeAgendamentoInvalido {
            get {
                return ResourceManager.GetString("DataDeAgendamentoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento inválido..
        /// </summary>
        public static string DataDeNascimentoInvalido {
            get {
                return ResourceManager.GetString("DataDeNascimentoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento é obrigatório..
        /// </summary>
        public static string DataDeNascimentoObrigatorio {
            get {
                return ResourceManager.GetString("DataDeNascimentoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDD é obrigatório..
        /// </summary>
        public static string DDDObrigatorio {
            get {
                return ResourceManager.GetString("DDDObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDD em tamanho incorreto..
        /// </summary>
        public static string DDDTamanhoInvalido {
            get {
                return ResourceManager.GetString("DDDTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do Estabelecimento tem tamanho incorreto..
        /// </summary>
        public static string DescricaoEstabelecimentoTamanhoInvalido {
            get {
                return ResourceManager.GetString("DescricaoEstabelecimentoTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição é obrigatória..
        /// </summary>
        public static string DescricaoObrigatorio {
            get {
                return ResourceManager.GetString("DescricaoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do Tipo de Serviço em tamanho incorreto..
        /// </summary>
        public static string DescricaoTipoDeServicoTamanhoInvalido {
            get {
                return ResourceManager.GetString("DescricaoTipoDeServicoTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail em formato inválido..
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail já existente..
        /// </summary>
        public static string EmailJaExiste {
            get {
                return ResourceManager.GetString("EmailJaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é obrigatório..
        /// </summary>
        public static string EmailObrigatorio {
            get {
                return ResourceManager.GetString("EmailObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail em tamanho incorreto..
        /// </summary>
        public static string EmailTamanhoIncorreto {
            get {
                return ResourceManager.GetString("EmailTamanhoIncorreto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço é obrigatório..
        /// </summary>
        public static string EnderecoObrigatorio {
            get {
                return ResourceManager.GetString("EnderecoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estabelecimento é obrigatório..
        /// </summary>
        public static string EstabelecimentoObrigatorio {
            get {
                return ResourceManager.GetString("EstabelecimentoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado é inválido..
        /// </summary>
        public static string EstadoInvalido {
            get {
                return ResourceManager.GetString("EstadoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Função é obrigatório..
        /// </summary>
        public static string FuncaoObrigatorio {
            get {
                return ResourceManager.GetString("FuncaoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Função tem tamanho incorreto..
        /// </summary>
        public static string FuncaoTamanhoInvalido {
            get {
                return ResourceManager.GetString("FuncaoTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O funcionário é inválido..
        /// </summary>
        public static string FuncionarioInvalido {
            get {
                return ResourceManager.GetString("FuncionarioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O funcionário é obrigatório..
        /// </summary>
        public static string FuncionarioObrigatorio {
            get {
                return ResourceManager.GetString("FuncionarioObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O logo é obrigatório..
        /// </summary>
        public static string LogoObrigatorio {
            get {
                return ResourceManager.GetString("LogoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro é obrigatório..
        /// </summary>
        public static string LogradouroObrigatorio {
            get {
                return ResourceManager.GetString("LogradouroObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome fantasia é obrigatório..
        /// </summary>
        public static string NomeFantasiaObrigatorio {
            get {
                return ResourceManager.GetString("NomeFantasiaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Fantasia está no tamanho incorreto..
        /// </summary>
        public static string NomeFantasiaTamanhoInvalido {
            get {
                return ResourceManager.GetString("NomeFantasiaTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório..
        /// </summary>
        public static string NomeObrigatorio {
            get {
                return ResourceManager.GetString("NomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório..
        /// </summary>
        public static string NomeObrigatorio1 {
            get {
                return ResourceManager.GetString("NomeObrigatorio1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome em tamanho incorreto..
        /// </summary>
        public static string NomeTamanhoInvalido {
            get {
                return ResourceManager.GetString("NomeTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número é obrigatório..
        /// </summary>
        public static string NumeroObrigatorio {
            get {
                return ResourceManager.GetString("NumeroObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número é obrigatório..
        /// </summary>
        public static string NumeroObrigatorio1 {
            get {
                return ResourceManager.GetString("NumeroObrigatorio1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número em tamanho incorreto..
        /// </summary>
        public static string NumeroTamanhoInvalido {
            get {
                return ResourceManager.GetString("NumeroTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A razão social é obrigatória..
        /// </summary>
        public static string RazaoSocialObrigatorio {
            get {
                return ResourceManager.GetString("RazaoSocialObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razão Social está no tamanho incorreto..
        /// </summary>
        public static string RazaoSocialTamanhoInvalido {
            get {
                return ResourceManager.GetString("RazaoSocialTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha é obrigatória..
        /// </summary>
        public static string SenhaObrigatoria {
            get {
                return ResourceManager.GetString("SenhaObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas são iguais..
        /// </summary>
        public static string SenhasIguais {
            get {
                return ResourceManager.GetString("SenhasIguais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho da senha não corresponde..
        /// </summary>
        public static string SenhaTamanhoInvalido {
            get {
                return ResourceManager.GetString("SenhaTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente números..
        /// </summary>
        public static string SomenteNumero {
            get {
                return ResourceManager.GetString("SomenteNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone inválido..
        /// </summary>
        public static string TelefoneInvalido {
            get {
                return ResourceManager.GetString("TelefoneInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone é obrigatório..
        /// </summary>
        public static string TelefoneObrigatorio {
            get {
                return ResourceManager.GetString("TelefoneObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone em tamanho incorreto..
        /// </summary>
        public static string TelefoneTamanhoIncorreto {
            get {
                return ResourceManager.GetString("TelefoneTamanhoIncorreto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de serviço é inválido..
        /// </summary>
        public static string TipoDoServicoInvalido {
            get {
                return ResourceManager.GetString("TipoDoServicoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O titulo do Tipo de Serviço é obrigatório..
        /// </summary>
        public static string TituloTipoDeServicoObrigatorio {
            get {
                return ResourceManager.GetString("TituloTipoDeServicoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O título do Tipo de Serviço em tamanho incorreto..
        /// </summary>
        public static string TituloTipoDeServicoTamanhoIncorreto {
            get {
                return ResourceManager.GetString("TituloTipoDeServicoTamanhoIncorreto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário é obrigatório..
        /// </summary>
        public static string UsuarioObrigatorio {
            get {
                return ResourceManager.GetString("UsuarioObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha inválidos..
        /// </summary>
        public static string UsuarioSenhaInvalido {
            get {
                return ResourceManager.GetString("UsuarioSenhaInvalido", resourceCulture);
            }
        }
    }
}
